# Generated by Django 5.2.6 on 2025-11-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_temporary_password',
            field=models.BooleanField(default=False),
        ),
    ]
