name: CI Pipeline



on:
  push:
    branches:
      - main
      - Stacey
  pull_request:
    branches:
      - main


jobs:
  frontend:
    name: Build & Test Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Run Build
        working-directory: frontend
        run: npx vite build

      - name: Run Lint
        working-directory: frontend
        run: npm run lint

      - name: Run Tests
        working-directory: frontend
        run: npm test

  backend:
    name: Build & Test Backend
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mall_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        working-directory: backend
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mall_db
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
        run: python manage.py migrate

      - name: Run tests
        working-directory: backend
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mall_db
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
        run: python manage.py test
